// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: debts.sql

package database

import (
	"context"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (created_at, modified_at, user_id, transaction_id, amount)
VALUES (?,?,?,?,?)
RETURNING id, transaction_id, user_id, amount, created_at, modified_at
`

type CreateDebtParams struct {
	CreatedAt     int64   `json:"created_at"`
	ModifiedAt    int64   `json:"modified_at"`
	UserID        int64   `json:"user_id"`
	TransactionID int64   `json:"transaction_id"`
	Amount        float64 `json:"amount"`
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRowContext(ctx, createDebt,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.UserID,
		arg.TransactionID,
		arg.Amount,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.UserID,
		&i.Amount,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
